const app = document.querySelector('#app');

const modules = [
  ['Reality Feedback Engine','Feeds observed outcomes back into decisions and predictions.'],['Outcome Attribution Engine','Tests how strongly an outcome can be attributed to an action.'],['Confidence Calibration','Adjusts confidence from measured prediction performance.'],['Experiment Design Engine','Turns uncertainty into controlled, reversible experiments.'],['A/B Strategy Evaluation','Compares strategies using measurable outcomes.'],['Regression Intelligence','Detects when an upgrade makes another capability worse.'],['Drift Detection','Detects changes in data, behavior, requirements, or environment.'],['Causal Outcome Ledger','Records outcomes, candidate causes, evidence, and attribution confidence.'],['Capability Benchmark Suite','Measures capabilities against repeatable scenarios and outcomes.'],['Reality Grounding Gate','Blocks consequential decisions based on unsupported assumptions.'],['Learning Quality Controller','Prevents weak evidence from becoming false lessons.'],['Prediction-to-Outcome Memory','Connects predictions, confidence, actions, outcomes, and lessons.']
];
const loop = [['Mission','Define the outcome that matters.'],['Context','Understand state, history, constraints, dependencies, and uncertainty.'],['Decision','Choose the highest-value safe action from available evidence.'],['Action','Execute the smallest useful step.'],['Observation','Capture what actually happened.'],['Reality Grounding','Separate observed evidence from inference and assumption.'],['Feedback','Compare prediction with outcome and measure error.'],['Attribution','Evaluate candidate causes instead of assuming causation.'],['Calibration','Update confidence from prediction performance.'],['Learning','Accept, reject, or hold lessons based on evidence quality.'],['Benchmark','Check whether capability actually improved.'],['Next Decision','Use verified learning to choose the next action.']];

const pages = {
  home:{label:'00 · OVERVIEW',title:'Think. Act. <span>Measure reality.</span>',intro:'GKFXL OS is a personal AI operating system for turning ideas into reliable, testable outcomes.',body:`<div class="hero-grid"><div><p class="eyebrow">CURRENT SYSTEM · v6.4</p><h1>Think. Act.<br><span>Measure reality.</span></h1><p class="lead">A closed-loop evidence-to-outcome system where reality outranks intention, predictions meet outcomes, and failures become controlled learning signals.</p><div class="actions"><button data-page="architecture" class="primary">Explore architecture</button><button data-page="modules" class="secondary">View intelligence layer</button></div></div><div class="system-orbit"><div class="orbit-ring r1"></div><div class="orbit-ring r2"></div><div class="orbit-core">GK<span>v6.4</span></div><b class="orbit-node o1">REALITY</b><b class="orbit-node o2">DECISION</b><b class="orbit-node o3">LEARNING</b><b class="orbit-node o4">OUTCOME</b></div></div><div class="stats"><div><b>v6.4</b><span>integrated architecture</span></div><div><b>12+</b><span>reality mechanisms</span></div><div><b>1</b><span>core principle: reality wins</span></div></div>`},
  architecture:{label:'01 · ARCHITECTURE',title:'One system. <span>One closed loop.</span>',intro:'The v6.4 architecture connects every major capability into one evidence-driven control cycle.',body:`<div class="architecture-flow">${loop.map((x,i)=>`<button class="flow-step" data-step="${i}"><small>${String(i+1).padStart(2,'0')}</small><strong>${x[0]}</strong><span>${x[1]}</span></button>`).join('')}</div><div id="step-detail" class="detail-panel"><small>SELECT A STAGE</small><h3>Mission</h3><p>Define the outcome that matters before implementation begins.</p></div><div class="rule-grid"><article><b>PASS</b><p>Sufficient evidence and acceptable risk.</p></article><article><b>HOLD</b><p>More verification or evidence is required.</p></article><article><b>REJECT</b><p>Evidence or safety is insufficient.</p></article><article><b>ESCALATE</b><p>Uncertainty or consequence exceeds the safe boundary.</p></article></div>`},
  modules:{label:'02 · INTELLIGENCE',title:'Reality & Evaluation <span>Layer.</span>',intro:'Cross-cutting mechanisms make the operating system measurable, grounded, and capable of learning from outcomes.',body:`<div class="module-grid">${modules.map((m,i)=>`<article class="module-card"><div class="module-number">${String(i+1).padStart(2,'0')}</div><h3>${m[0]}</h3><p>${m[1]}</p></article>`).join('')}</div>`},
  reality:{label:'03 · REALITY ENGINE',title:'Reality <span>outranks intention.</span>',intro:'Important claims must pass through evidence, verification, freshness, uncertainty, and consequence checks.',body:`<div class="reality-board"><div class="claim"><small>CLAIM STATE</small><strong>OBSERVED</strong><p>Directly measured or witnessed evidence.</p></div><div class="claim"><small>CLAIM STATE</small><strong>SUPPORTED</strong><p>Backed by reliable evidence.</p></div><div class="claim"><small>CLAIM STATE</small><strong>INFERRED</strong><p>A conclusion derived from available evidence.</p></div><div class="claim warning"><small>CLAIM STATE</small><strong>ASSUMED</strong><p>Useful working belief, but not established as fact.</p></div><div class="claim unknown"><small>CLAIM STATE</small><strong>UNKNOWN</strong><p>Evidence is insufficient or unavailable.</p></div></div><div class="reality-rule"><strong>Built ≠ Working</strong><span>·</span><strong>Working ≠ Verified</strong><span>·</span><strong>Verified ≠ Successful</strong></div>`},
  evaluation:{label:'04 · EVALUATION',title:'Measure whether the system <span>actually improved.</span>',intro:'A new feature is not automatically an improvement. GKFXL OS requires measurable evidence.',body:`<div class="evaluation-grid"><article><span>01</span><h3>Benchmark</h3><p>Establish a baseline, target, scenario, expected result, observed result, evidence, and score.</p></article><article><span>02</span><h3>Regression</h3><p>Re-test existing capabilities after every meaningful change.</p></article><article><span>03</span><h3>Drift</h3><p>Detect when the environment or requirements change enough to invalidate old assumptions.</p></article><article><span>04</span><h3>Calibration</h3><p>Compare confidence against actual prediction accuracy.</p></article></div><div class="formula">PREDICTION → ACTION → OUTCOME → ERROR → ATTRIBUTION → LEARNING → BENCHMARK</div>`},
  evolution:{label:'05 · EVOLUTION',title:'From reasoning framework to <span>learning system.</span>',intro:'GKFXL OS preserves its evolution history while adding stronger controls only when they improve the integrated system.',body:`<div class="timeline"><article><b>v1</b><h3>Reasoning Framework</h3><p>Initial reasoning and decision framework.</p></article><article><b>v2.0</b><h3>Operating System</h3><p>Mission Control, Context Engine, Guardians, Decision Engine, Product Engine, recovery, health scoring, and STOP → THINK → ACT.</p></article><article><b>v6.2</b><h3>Integrated Core</h3><p>Expanded cross-cutting controls and mature operating workflow.</p></article><article><b>v6.3</b><h3>Reality & Evaluation</h3><p>Feedback, attribution, calibration, experiments, A/B evaluation, regression, drift, grounding, learning quality, and prediction memory.</p></article><article class="current"><b>v6.4</b><h3>Reality-to-Outcome Architecture</h3><p>All major reality and evaluation mechanisms operate as one closed-loop evidence-to-outcome system.</p></article></div>`},
  docs:{label:'06 · DOCUMENTATION',title:'The operating rules <span>behind the system.</span>',intro:'GKFXL OS is designed as a practical engineering framework, not a collection of fashionable AI features.',body:`<div class="docs-grid"><a href="../README.md"><b>README</b><span>System overview and principles</span></a><a href="../VERSION.md"><b>VERSION</b><span>Current release definition</span></a><a href="../CHANGELOG.md"><b>CHANGELOG</b><span>Evolution history</span></a><a href="../core/V6.4-INTEGRATION-ARCHITECTURE.md"><b>ARCHITECTURE</b><span>Integrated control loop</span></a><a href="../protocols/STOP-THINK-ACT.md"><b>PROTOCOL</b><span>STOP → THINK → ACT → LEARN</span></a><a href="https://github.com/gokulmaniraj2008-collab/GKFXL-OS" target="_blank" rel="noreferrer"><b>GITHUB ↗</b><span>Full source and specifications</span></a></div>`}
};

function render(page='home'){
 const p=pages[page]||pages.home;
 app.innerHTML=`<header class="nav"><button class="brand" data-page="home"><span class="brand-mark">G</span>GKFXL <em>OS</em></button><nav>${Object.entries({home:'System',architecture:'Architecture',modules:'Modules',reality:'Reality',evaluation:'Evaluation',evolution:'Evolution',docs:'Docs'}).map(([k,v])=>`<button data-page="${k}" class="${page===k?'active':''}">${v}</button>`).join('')}</nav><a class="github" href="https://github.com/gokulmaniraj2008-collab/GKFXL-OS" target="_blank" rel="noreferrer">GitHub ↗</a><button class="menu" id="menu">☰</button></header><main><section class="page-head"><p class="eyebrow">${p.label}</p><h2>${p.title}</h2><p>${p.intro}</p></section><section class="page-content">${p.body}</section></main><footer><span>GKFXL OS · v6.4</span><span>Reality · Evidence · Outcome · Learning</span></footer>`;
 bind(); window.scrollTo({top:0,behavior:'smooth'});
}
function bind(){
 document.querySelectorAll('[data-page]').forEach(el=>el.addEventListener('click',()=>render(el.dataset.page)));
 document.querySelector('#menu')?.addEventListener('click',()=>document.querySelector('.nav nav').classList.toggle('open'));
 document.querySelectorAll('.flow-step').forEach(btn=>btn.addEventListener('click',()=>{const x=loop[Number(btn.dataset.step)];document.querySelector('#step-detail').innerHTML=`<small>STAGE ${String(Number(btn.dataset.step)+1).padStart(2,'0')}</small><h3>${x[0]}</h3><p>${x[1]}</p>`;document.querySelectorAll('.flow-step').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected')}));
}
render();
